/*
 * Writes data.c: the files arv shares between its Python and C versions, as C arrays.
 *
 *   embed OUT.c NAME=FILE...
 *
 * data.c is generated but committed, so arv builds with one cc line from a disc's tools/;
 * make check fails if it is out of date.
 */
#include <stdio.h>
#include <string.h>

int main(int argc, char **argv)
{
    FILE *out = argc > 1 ? fopen(argv[1], "w") : NULL;
    if (!out) {
        fputs("usage: embed OUT.c NAME=FILE...\n", stderr);
        return 2;
    }
    fputs("/* Generated by dev-tools/embed.c from the files named below: do not edit; run make data. */\n"
          "#include \"data.h\"\n", out);
    for (int i = 2; i < argc; i++) {
        char *eq = strchr(argv[i], '=');
        FILE *in = eq ? fopen(eq + 1, "rb") : NULL;
        int c, n = 0;
        if (!in) {
            fprintf(stderr, "embed: cannot read %s\n", argv[i]);
            return 1;
        }
        *eq = 0;
        fprintf(out, "\n/* %s */\nconst char %s[] = {", strrchr(eq + 1, '/') ? strrchr(eq + 1, '/') + 1 : eq + 1, argv[i]);
        while ((c = getc(in)) != EOF) fprintf(out, "%s%d,", n++ % 24 ? "" : "\n    ", c);
        fprintf(out, "\n    0\n};\n");
        fclose(in);
    }
    return fclose(out) ? 1 : 0;
}
